spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:9296
  datasource:
    username: order_user
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order
  banner:
    location: orderServiceBanner.txt

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8080/eureka}

server:
  port: 8082

#management:
#  tracing:
#    sampling:
#      probability: 1.0
