spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:9296
  datasource:
    username: order_user
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order
  banner:
    location: orderServiceBanner.txt
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-14992024.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaegd5kajm5M6zFi5d7
            client-secret: bhCrYLNiRAyXqeG3JzWrh0NaKRMYZW8OiO6uT-6GFGH5WS-nmT6FqRQY7SbnvTzy
        provider:
          okta:
            issuer-uri: https://dev-14992024.okta.com/oauth2/default

server:
  port: 8082

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
